grails-app/domain/volp/Role.groovy
package volp

class Role {

    String role
    int sort_order
    String role_displayname
    boolean isRoleSet
    String username    
    Date creation_date
    Date updation_date
    String creation_ip_address
    String updation_ip_address    
    static belongsTo=[roletype:RoleType,usertype:UserType,organization:Organization]
    static constraints = {
        organization nullable: true
    	role nullable:false
        usertype nullable:true
        role_displayname nullable:true
    }
    String toString(){
    	role
    }
}

grails-app/domain/volp/RoleType.groovy
package volp

class RoleType {

    String icon_path
    String type  //modules
    String type_displayname  //modules
    boolean isroletypeset
    boolean isactive
    int sort_order
    boolean isapplicabletolearnercurrentyear
    boolean isapplicableforpushingtonextyear

    String username    
    Date creation_date
    Date updation_date
    String creation_ip_address
    String updation_ip_address
    static belongsTo=[applicationtype:ApplicationType, organization:Organization]
    static constraints = {
        icon_path nullable:true
    	type nullable:false
        isapplicabletolearnercurrentyear nullable:false
        type_displayname nullable:true
        isactive defaultValue: true
    }
    String toString(){
        type
    }
    static mapping = {
        isapplicableforpushingtonextyear defaultValue: false
    }
}

grails-app/controllers/volp/RoleController.groovy
package volp

import grails.validation.ValidationException
import static org.springframework.http.HttpStatus.*

class RoleController {

    RoleService roleService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    def registrarRoleLinks()
    {
        ////println("In registrarRoleLink  : " + params)
        Login login=Login.findById(session.loginid)
        Instructor instructor=Instructor.findByUid(login.username)

        RoleType rt = RoleType.findByTypeAndOrganization("Leave Management", instructor.organization)
        Role r =  Role.findByRoleAndRoletypeAndOrganization("Registrar",rt, instructor.organization)
        def registrarroleLinks = RoleLink.findAllByOrganizationAndRole(instructor.organization,r)

        r =  Role.findByRoleAndRoletypeAndOrganization("HOD",rt, instructor.organization)
        def hodroleLinks = RoleLink.findAllByOrganizationAndRole(instructor.organization,r)


        r =  Role.findByRoleAndRoletypeAndOrganization("Establishment Section",rt, instructor.organization)
        def estroleLinks = RoleLink.findAllByOrganizationAndRole(instructor.organization,r)


        r =  Role.findByRoleAndRoletypeAndOrganization("Faculty",rt, instructor.organization)
        def selfroleLinks = RoleLink.findAllByOrganizationAndRole(instructor.organization,r)

        [registrarroleLinks:registrarroleLinks , hodroleLinks:hodroleLinks,estroleLinks:estroleLinks,selfroleLinks:selfroleLinks]
    }

  /*  def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond roleService.list(params), model:[roleCount: roleService.count()]
    }

    def show(Long id) {
        respond roleService.get(id)
    }

    def create() {
        respond new Role(params)
    }

    def save(Role role) {
        if (role == null) {
            notFound()
            return
        }

        try {
            roleService.save(role)
        } catch (ValidationException e) {
            respond role.errors, view:'create'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'role.label', default: 'Role'), role.id])
                redirect role
            }
            '*' { respond role, [status: CREATED] }
        }
    }

    def edit(Long id) {
        respond roleService.get(id)
    }

    def update(Role role) {
        if (role == null) {
            notFound()
            return
        }

        try {
            roleService.save(role)
        } catch (ValidationException e) {
            respond role.errors, view:'edit'
            return
        }

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'role.label', default: 'Role'), role.id])
                redirect role
            }
            '*'{ respond role, [status: OK] }
        }
    }

    def delete(Long id) {
        if (id == null) {
            notFound()
            return
        }

        roleService.delete(id)

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'role.label', default: 'Role'), id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'role.label', default: 'Role'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    } */
}

grails-app/views/role/create.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
        <title><g:message code="default.create.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#create-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="create-role" class="content scaffold-create" role="main">
            <h1><g:message code="default.create.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.role}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.role}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.role}" method="POST">
                <fieldset class="form">
                    <f:all bean="role"/>
                </fieldset>
                <fieldset class="buttons">
                    <g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/role/edit.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
        <title><g:message code="default.edit.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#edit-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="edit-role" class="content scaffold-edit" role="main">
            <h1><g:message code="default.edit.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <g:hasErrors bean="${this.role}">
            <ul class="errors" role="alert">
                <g:eachError bean="${this.role}" var="error">
                <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
            </g:hasErrors>
            <g:form resource="${this.role}" method="PUT">
                <g:hiddenField name="version" value="${this.role?.version}" />
                <fieldset class="form">
                    <f:all bean="role"/>
                </fieldset>
                <fieldset class="buttons">
                    <input class="save" type="submit" value="${message(code: 'default.button.update.label', default: 'Update')}" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>

grails-app/views/role/index.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
        <title><g:message code="default.list.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#list-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="list-role" class="content scaffold-list" role="main">
            <h1><g:message code="default.list.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:table collection="${roleList}" />

            <div class="pagination">
                <g:paginate total="${roleCount ?: 0}" />
            </div>
        </div>
    </body>
</html>

grails-app/views/role/registrarRoleLinks.gsp
<head>
    <meta name="layout" content="ERPmainTemplateT2">


    <style>
           #spinner {
             position: fixed;
             top: 50%;
             left: 50%;
             margin-left: -50px; // half width of the spinner gif
             margin-top: -50px; // half height of the spinner gif
             z-index: 5000;
             overflow: auto;
           }
           .loader {
             border: 10px solid #f3f3f3;
             border-radius: 50%;
             //border-top: 16px solid #333;


              border-top: 6px solid #80BD9E;
              border-right: 6px solid #89DA59;
              border-bottom: 6px solid #FF420E;
              border-left: 6px solid #F98866;


             width: 45px;
             height: 45px;
             -webkit-animation: spin 2s linear infinite; /* Safari */
             animation: spin 2s linear infinite;
           }

           /* Safari */
           @-webkit-keyframes spin {
             0% { -webkit-transform: rotate(0deg); }
             100% { -webkit-transform: rotate(360deg); }
           }

           @keyframes spin {
             0% { transform: rotate(0deg); }
             100% { transform: rotate(360deg); }
           }
           </style>
</head>

<!-- Page Content  Copy Coding use Only-------------------------------------->
<div id="page-wrapper">
    <div class="container-fluid">
        <g:render template="/layouts/home_back_btn_T2"/>

        <div class="row">
            <div class="col-lg-12">

                <h3 class="page-header" style="text-align: center;">Links</h3>

                 <!-- Start coding only in This block ------------------->

                 <div id="update"></div>
                 <table class="table table-striped table-bordered"  >
                 <thead>
                     <tr class="alert-dark" >
                          <th>Registrar</th>

                     </tr>
                 </thead>
                     <tbody >

                           <g:each var="rolelink" in="${registrarroleLinks}">
                            <tr >
                                  <td>
                                       <g:link  action="${rolelink.action_name}"
                                                                          controller="${rolelink.controller_name}" >
                                                                                  <label style="background: white;opacity: 0.9; color:blue;">
                                                                                  ${rolelink.link_name}
                                                                                  </label>
                                                                          </g:link>
                                  </td>

                              </tr>
                          </g:each >

                      </tbody>
                  </table>

                   <table class="table table-striped table-bordered"  >
                       <thead>
                           <tr class="alert-dark" >
                                <th>Establishment Section </th>

                           </tr>
                       </thead>
                           <tbody >

                                 <g:each var="rolelink" in="${estroleLinks}">
                                  <tr >
                                        <td>
                                             <g:link  action="${rolelink.action_name}"
                                                                                controller="${rolelink.controller_name}" >
                                                                                        <label style="background: white;opacity: 0.9; color:blue;">
                                                                                        ${rolelink.link_name}
                                                                                        </label>
                                                                                </g:link>
                                        </td>

                                    </tr>
                                </g:each >

                            </tbody>
                        </table>

                  <table class="table table-striped table-bordered"  >
                   <thead>
                       <tr class="alert-dark" >
                            <th>HOD</th>

                       </tr>
                   </thead>
                       <tbody >

                             <g:each var="rolelink" in="${hodroleLinks}">
                              <tr >
                                    <td>
                                         <g:link  action="${rolelink.action_name}"
                                                                            controller="${rolelink.controller_name}" >
                                                                                    <label style="background: white;opacity: 0.9; color:blue;">
                                                                                    ${rolelink.link_name}
                                                                                    </label>
                                                                            </g:link>
                                    </td>

                                </tr>
                            </g:each >

                        </tbody>
                    </table>


                    <table class="table table-striped table-bordered"  >
                   <thead>
                       <tr class="alert-dark" >
                            <th>SELF</th>
                       </tr>
                   </thead>
                       <tbody >
                             <g:each var="rolelink" in="${selfroleLinks}">
                              <tr >
                                    <td>
                                         <g:link  action="${rolelink.action_name}"
                                            controller="${rolelink.controller_name}" >
                                                    <label style="background: white;opacity: 0.9; color:blue;">
                                                    ${rolelink.link_name}
                                                    </label>
                                            </g:link>
                                    </td>


                                </tr>
                            </g:each >

                        </tbody>
                    </table>
            </div>
            <!-- /.col-lg-12 -->
        </div> <!-- /.row -->


    </div> <!-- /.container-fluid -->
<script>
function changeLeaveMaster(val)
{
    alert("ChangeLeaveMaster"+val);
}
</script>


</div>
<!-- /#page-wrapper  Page Content  Copy Coding use Only------------------------------------- -->

 <script>

function showSpinner() {
               document.getElementById('spinner').style.display = 'inline';
               document.getElementById('error').style.display = 'none';
           }

           function hideSpinner() {
               document.getElementById('spinner').style.display = 'none';
               document.getElementById('error').style.display = 'none';
           }

           function showError(e) {
               var errorDiv = document.getElementById('error')
               errorDiv.innerHTML = '<ul><li>'
                        + e.responseText + '</li></ul>';
               errorDiv.style.display = 'block';
           }

   </script>

grails-app/views/role/show.gsp
<!DOCTYPE html>
<html>
    <head>
        <meta name="layout" content="main" />
        <g:set var="entityName" value="${message(code: 'role.label', default: 'Role')}" />
        <title><g:message code="default.show.label" args="[entityName]" /></title>
    </head>
    <body>
        <a href="#show-role" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
        <div class="nav" role="navigation">
            <ul>
                <li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
                <li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
                <li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
            </ul>
        </div>
        <div id="show-role" class="content scaffold-show" role="main">
            <h1><g:message code="default.show.label" args="[entityName]" /></h1>
            <g:if test="${flash.message}">
            <div class="message" role="status">${flash.message}</div>
            </g:if>
            <f:display bean="role" />
            <g:form resource="${this.role}" method="DELETE">
                <fieldset class="buttons">
                    <g:link class="edit" action="edit" resource="${this.role}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
                    <input class="delete" type="submit" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
                </fieldset>
            </g:form>
        </div>
    </body>
</html>